/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flinsafeprototype;

import javax.swing.JFrame;

/**
 *
 * @author dkear
 */
public class KioskReportSelectionPanel extends javax.swing.JPanel {

    JFrame parent;
    
    /**
     * Creates new form KioskReportSelectionPanel
     */
    public KioskReportSelectionPanel() {
        initComponents();
    }
    public KioskReportSelectionPanel(JFrame parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fireButton = new javax.swing.JButton();
        accessButton = new javax.swing.JButton();
        escortButton = new javax.swing.JButton();
        injuryButton = new javax.swing.JButton();
        snakeButton = new javax.swing.JButton();
        intruderButton = new javax.swing.JButton();
        otherButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(12, 13, 100, 50);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Report Incident");
        add(jLabel1);
        jLabel1.setBounds(561, 13, 260, 47);

        fireButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/FIRE_1.png"))); // NOI18N
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });
        add(fireButton);
        fireButton.setBounds(190, 120, 200, 150);

        accessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/request Access.png"))); // NOI18N
        accessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessButtonActionPerformed(evt);
            }
        });
        add(accessButton);
        accessButton.setBounds(560, 440, 200, 150);

        escortButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/escort.png"))); // NOI18N
        escortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escortButtonActionPerformed(evt);
            }
        });
        add(escortButton);
        escortButton.setBounds(290, 440, 200, 150);

        injuryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/injury.png"))); // NOI18N
        injuryButton.setMaximumSize(new java.awt.Dimension(83, 37));
        injuryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuryButtonActionPerformed(evt);
            }
        });
        add(injuryButton);
        injuryButton.setBounds(980, 120, 200, 150);

        snakeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/Eastern-Brown-Snake.png"))); // NOI18N
        snakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snakeButtonActionPerformed(evt);
            }
        });
        add(snakeButton);
        snakeButton.setBounds(460, 120, 200, 160);

        intruderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/Intruder.png"))); // NOI18N
        intruderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intruderButtonActionPerformed(evt);
            }
        });
        add(intruderButton);
        intruderButton.setBounds(720, 120, 200, 150);

        otherButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        otherButton.setText("Other");
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });
        add(otherButton);
        otherButton.setBounds(820, 440, 200, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/flindersbackgroundfaded.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1370, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parent.setContentPane(new KioskMainScreenPanel(parent));
        parent.revalidate();
    }//GEN-LAST:event_backButtonActionPerformed

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        parent.setContentPane(new KioskFireDetailsPanel(parent, "fire"));
        parent.revalidate();
    }//GEN-LAST:event_fireButtonActionPerformed

    private void accessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessButtonActionPerformed
        parent.setContentPane(new KioskAccessDetailsPanel1(parent, "access"));
        parent.revalidate();
    }//GEN-LAST:event_accessButtonActionPerformed

    private void escortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escortButtonActionPerformed
        parent.setContentPane(new KioskEscortDetailsPanel(parent, "escort"));
        parent.revalidate();
    }//GEN-LAST:event_escortButtonActionPerformed

    private void injuryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuryButtonActionPerformed
        parent.setContentPane(new KioskInjuryDetailsPanel(parent, "injury"));
        parent.revalidate();
    }//GEN-LAST:event_injuryButtonActionPerformed

    private void snakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snakeButtonActionPerformed
        parent.setContentPane(new KioskSnakeDetailsPanel(parent, "snake"));
        parent.revalidate();
    }//GEN-LAST:event_snakeButtonActionPerformed

    private void intruderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intruderButtonActionPerformed
        parent.setContentPane(new KioskIntruderDetailsPanel1(parent, "intruder"));
        parent.revalidate();
    }//GEN-LAST:event_intruderButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        parent.setContentPane(new KioskIncidentDetailsPanel(parent, "other"));
        parent.revalidate();
    }//GEN-LAST:event_otherButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton escortButton;
    private javax.swing.JButton fireButton;
    private javax.swing.JButton injuryButton;
    private javax.swing.JButton intruderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton otherButton;
    private javax.swing.JButton snakeButton;
    // End of variables declaration//GEN-END:variables
}
