/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flinsafeprototype;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dkear
 *
 * MainMenu is used as a dispatch screen for each of the bits of functionality
 * implemented in this assignment
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() throws IOException {
        String fileString;
        File fileFile;
        try {
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "IncidentQueue.csv";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "NewIncidents.csv";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "Reports.csv";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "InProgress.csv";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "flindersmap.png";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }
            fileString = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "mappinsmall.png";
            fileFile = new File(fileString);
            if(!fileFile.exists()){
                throw new Exception();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "The system could not find one of the necessary files.\n Please ensure that the directory with the .jar files in it contains the following files:\n - NewIncidents.csv \n - IncidentQueue.csv \n - Reports.csv \n - InProgress.csv \n - flindersmap.png \n - mappinsmall.png");
            System.exit(0);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectFeatureLabel = new javax.swing.JLabel();
        kioskButton = new javax.swing.JButton();
        securitySummaryButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        phoneAppButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainMenu");
        setName("MainMenu"); // NOI18N

        selectFeatureLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectFeatureLabel.setForeground(new java.awt.Color(0, 51, 204));
        selectFeatureLabel.setText("Select a Prototype Feature");

        kioskButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kioskButton.setText("FlinSafe Kiosk");
        kioskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kioskButtonActionPerformed(evt);
            }
        });

        securitySummaryButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securitySummaryButton.setText("Security Summary");
        securitySummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securitySummaryButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinders-university-logo.png"))); // NOI18N
        jLabel1.setOpaque(true);

        phoneAppButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneAppButton.setText("FlinSafe Phone App");
        phoneAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneAppButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kioskButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(securitySummaryButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneAppButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectFeatureLabel)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFeatureLabel)
                .addGap(18, 18, 18)
                .addComponent(kioskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(securitySummaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void securitySummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securitySummaryButtonActionPerformed
        try {
            new SecuritySummaryMain().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_securitySummaryButtonActionPerformed

    private void kioskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kioskButtonActionPerformed
        new KioskFrame().setVisible(true);
    }//GEN-LAST:event_kioskButtonActionPerformed

    private void phoneAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneAppButtonActionPerformed
        new PhoneFrame().setVisible(true);
    }//GEN-LAST:event_phoneAppButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMenu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kioskButton;
    private javax.swing.JButton phoneAppButton;
    private javax.swing.JButton securitySummaryButton;
    private javax.swing.JLabel selectFeatureLabel;
    // End of variables declaration//GEN-END:variables
}
