/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flinsafeprototype;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author dkear
 */
public class SecuritySummaryInProgressReportResultPanel extends javax.swing.JPanel {
    
    private String[] incidentInfo;
    javax.swing.JFrame parent;
    SecuritySummaryMain home;
    JPanel source;
    
    /**
     * Creates new form SecuritySummaryInProgressReportResultPanel
     */
    public SecuritySummaryInProgressReportResultPanel() {
        initComponents();
    }
    public SecuritySummaryInProgressReportResultPanel(SecuritySummaryMain home, SecuritySummaryInProgressResponse parent, JPanel source) {
        this.parent = parent;
        this.home = home;
        this.source = source;
        incidentInfo = parent.getIncidentInfo();
        HelperLocations locs = new HelperLocations();
        initComponents();
        this.incidentInfo = incidentInfo;
        System.out.println(this.getWidth());
        parent.setSize(new Dimension(820, 960));
        
        timeLabel.setText(incidentInfo[2]);
        numLabel.setText(incidentInfo[0]);
        typeLabel.setText(incidentInfo[3]);
        locationLabel.setText(incidentInfo[6]);
        commentsTextArea.setText(incidentInfo[5]);
        responderLabel.setText(incidentInfo[4]);
        responseStartTimeLabel.setText(incidentInfo[1]);
    }
    public SecuritySummaryInProgressReportResultPanel(SecuritySummaryMain home, SecuritySummaryNewIncidentResponse parent) {
        this.parent = parent;
        this.home = home;
        incidentInfo = parent.getIncidentInfo();
        HelperLocations locs = new HelperLocations();
        initComponents();
        this.incidentInfo = incidentInfo;
        System.out.println(this.getWidth());
        parent.setSize(new Dimension(761, 805));
        
        timeLabel.setText(incidentInfo[2]);
        numLabel.setText(incidentInfo[0]);
        typeLabel.setText(incidentInfo[3]);
        locationLabel.setText(incidentInfo[6]);
        commentsTextArea.setText(incidentInfo[5]);
        responderLabel.setText(incidentInfo[4]);
        responseStartTimeLabel.setText(incidentInfo[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        responderLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        responseStartTimeLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        reportTitleTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reportSummaryTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        reportResolutionTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        reportResultComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportTextTextArea = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Completed Incident Report Form");
        add(jLabel1);
        jLabel1.setBounds(130, 100, 520, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Report Details");
        add(jLabel2);
        jLabel2.setBounds(299, 457, 150, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Incident Number");
        add(jLabel3);
        jLabel3.setBounds(43, 185, 132, 22);

        numLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        numLabel.setText("jLabel9");
        add(numLabel);
        numLabel.setBounds(201, 187, 240, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Report Type");
        add(jLabel4);
        jLabel4.setBounds(78, 212, 97, 22);

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        typeLabel.setText("jLabel9");
        add(typeLabel);
        typeLabel.setBounds(201, 214, 240, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Report Time");
        add(jLabel6);
        jLabel6.setBounds(78, 241, 97, 22);

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timeLabel.setText("jLabel9");
        add(timeLabel);
        timeLabel.setBounds(201, 243, 260, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Report Location");
        add(jLabel7);
        jLabel7.setBounds(51, 270, 124, 22);

        locationLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        locationLabel.setText("jLabel9");
        add(locationLabel);
        locationLabel.setBounds(201, 272, 270, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Responder");
        add(jLabel9);
        jLabel9.setBounds(92, 299, 83, 22);

        responderLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        responderLabel.setText("jLabel9");
        add(responderLabel);
        responderLabel.setBounds(201, 301, 290, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Response Start Time");
        add(jLabel10);
        jLabel10.setBounds(12, 328, 163, 22);

        responseStartTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        responseStartTimeLabel.setText("jLabel9");
        add(responseStartTimeLabel);
        responseStartTimeLabel.setBounds(201, 330, 270, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Report Comments");
        add(jLabel8);
        jLabel8.setBounds(33, 357, 142, 22);

        commentsTextArea.setEditable(false);
        commentsTextArea.setBackground(new java.awt.Color(240, 240, 240));
        commentsTextArea.setColumns(20);
        commentsTextArea.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        commentsTextArea.setLineWrap(true);
        commentsTextArea.setRows(5);
        commentsTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(commentsTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(201, 357, 524, 87);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Incident Details:");
        add(jLabel5);
        jLabel5.setBounds(12, 145, 172, 29);

        reportTitleTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(reportTitleTextField);
        reportTitleTextField.setBounds(193, 507, 162, 26);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Report Title:");
        add(jLabel11);
        jLabel11.setBounds(77, 508, 98, 22);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("This should be only a couple of words describing the incident");
        add(jLabel12);
        jLabel12.setBounds(193, 540, 348, 16);

        reportSummaryTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(reportSummaryTextField);
        reportSummaryTextField.setBounds(193, 563, 532, 26);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Report Summary:");
        add(jLabel13);
        jLabel13.setBounds(37, 564, 138, 22);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Summarise the report in one sentence");
        add(jLabel14);
        jLabel14.setBounds(193, 596, 220, 16);

        reportResolutionTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(reportResolutionTextField);
        reportResolutionTextField.setBounds(193, 619, 532, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Report Resolution:");
        add(jLabel15);
        jLabel15.setBounds(29, 620, 146, 22);

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Summarise the resolution of the incident in one sentence");
        add(jLabel16);
        jLabel16.setBounds(193, 652, 326, 16);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Report Result:");
        add(jLabel17);
        jLabel17.setBounds(63, 682, 112, 22);

        reportResultComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reportResultComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resolved","Escalated","Resolved and Escalated" }));
        add(reportResultComboBox);
        reportResultComboBox.setBounds(193, 681, 232, 26);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Report Details:");
        add(jLabel18);
        jLabel18.setBounds(59, 720, 116, 22);

        reportTextTextArea.setColumns(20);
        reportTextTextArea.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reportTextTextArea.setLineWrap(true);
        reportTextTextArea.setRows(5);
        reportTextTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(reportTextTextArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(193, 720, 532, 106);

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Go into more detail about the incident");
        add(jLabel19);
        jLabel19.setBounds(193, 833, 215, 16);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Submit Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(320, 860, 200, 29);

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(30, 100, 80, 31);

        jLabel23.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel23.setText("FlinSafe: Incident Report Form");
        add(jLabel23);
        jLabel23.setBounds(380, 30, 380, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flinsafeprototype/flindersbanner.png"))); // NOI18N
        jLabel21.setText("jLabel2");
        add(jLabel21);
        jLabel21.setBounds(-210, 0, 1240, 87);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parent.setContentPane(source);
        parent.setSize(1024, 550);
        parent.revalidate();
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //CSV FILE HERE
        //URL url = getClass().getResource("Reports.csv");
        //File file = new File(url.getPath());
        String file = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "Reports.csv";
        BufferedWriter writer = null;
        Calendar calendar = Calendar.getInstance();
        int hour = calendar.get(Calendar.HOUR_OF_DAY);
        int min = calendar.get(Calendar.MINUTE);

        //add to reports
        try {
            writer = new BufferedWriter(new FileWriter(file, true));
        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryNewIncidentResponse.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            System.out.println(incidentInfo[0] + ", " + new Date() + ",\"" + incidentInfo[2] + "\",\"" + reportTitleTextField.getText() + "\",\"" + reportSummaryTextField.getText() + "\",\"" + reportResolutionTextField.getText() + "\"," + incidentInfo[6] + "," + "Gerry Mortimer" + ",\"Security Guards Comments:" + reportTextTextArea.getText() + ";Reporter Comments:" + incidentInfo[5] + "\"," + incidentInfo[3] + "," + (String) reportResultComboBox.getSelectedItem());
            writer.append(incidentInfo[0] + ", " + new Date() + ",\"" + incidentInfo[2] + "\",\"" + reportTitleTextField.getText() + "\",\"" + reportSummaryTextField.getText() + "\",\"" + reportResolutionTextField.getText() + "\"," + incidentInfo[6] + "," + "Gerry Mortimer" + ",\"Security Guards Comments:" + reportTextTextArea.getText() + ";Reporter Comments:" + incidentInfo[5] + "\"," + incidentInfo[3] + "," + (String) reportResultComboBox.getSelectedItem());
            writer.newLine();

        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryNewIncidentResponse.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            writer.flush();
            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            home.readReports();
        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        //remove from in progress
        int id = Integer.parseInt(incidentInfo[0]);
        //CSV FILE HERE
        //url = getClass().getResource("InProgress.csv");
        //file = new File(url.getPath());
        file = new File(".").getAbsolutePath().substring(0,new File(".").getAbsolutePath().length() - 1) + "InProgress.csv";

        //read in all lines
        BufferedReader reader;
        LinkedList<String> stringList = new LinkedList<String>();
        try {
            reader = new BufferedReader(new FileReader(file));
            //reader.readLine();
            String currentLine;
            while((currentLine = reader.readLine()) != null){
                stringList.add(currentLine);
            }
            reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        //write all out except for the one we want to remove

        try {

            writer = new BufferedWriter(new FileWriter(file, false));
            String currentLine;
            currentLine = stringList.remove();
            writer.write(currentLine);
            writer.newLine();
            while(stringList.size() > 0){
                currentLine = stringList.remove();
                String[] incident = currentLine.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);
                if(Integer.parseInt(incident[0]) != id){
                    writer.write(currentLine);
                    writer.newLine();
                }
            }
            writer.close();
            home.readInProgress();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SecuritySummaryIncidentResponsePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        parent.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField reportResolutionTextField;
    private javax.swing.JComboBox<String> reportResultComboBox;
    private javax.swing.JTextField reportSummaryTextField;
    private javax.swing.JTextArea reportTextTextArea;
    private javax.swing.JTextField reportTitleTextField;
    private javax.swing.JLabel responderLabel;
    private javax.swing.JLabel responseStartTimeLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
