/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flinsafeprototype;

import java.awt.BorderLayout;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dkear
 *
 * Very barebones currently. It is essentially what security guards will have on
 * their computers.
 */
public class SecuritySummaryMain extends javax.swing.JFrame {

    /**
     * Creates new form securitySummary
     */
    public SecuritySummaryMain() throws IOException {
        initComponents();
        initTableListener();
        readReports();
        readNewIncidents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedMenu = new javax.swing.JTabbedPane();
        NewIncidentsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        newIncidentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tab1Queue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        incidentQueueTable = new javax.swing.JTable();
        inProgressPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inProgressTable = new javax.swing.JTable();
        recentlyResolvedPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        recentlyResolvedTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Security Summary Main");

        newIncidentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incident ID", "Report Type", "Report Location", "Report Time", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(newIncidentTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Options:");

        jButton1.setText("View Incident Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Straight to Queue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewIncidentsPanelLayout = new javax.swing.GroupLayout(NewIncidentsPanel);
        NewIncidentsPanel.setLayout(NewIncidentsPanelLayout);
        NewIncidentsPanelLayout.setHorizontalGroup(
            NewIncidentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewIncidentsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NewIncidentsPanelLayout.setVerticalGroup(
            NewIncidentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedMenu.addTab("New Incidents", NewIncidentsPanel);

        incidentQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incident ID", "Report Type", "Report Location", "Report Time", "Comments"
            }
        ));
        jScrollPane1.setViewportView(incidentQueueTable);

        javax.swing.GroupLayout tab1QueueLayout = new javax.swing.GroupLayout(tab1Queue);
        tab1Queue.setLayout(tab1QueueLayout);
        tab1QueueLayout.setHorizontalGroup(
            tab1QueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1QueueLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        tab1QueueLayout.setVerticalGroup(
            tab1QueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        tabbedMenu.addTab("Incident Queue", tab1Queue);

        inProgressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incident ID", "Report Type", "Report Location", "Report Time", "Responder", "Comments"
            }
        ));
        jScrollPane2.setViewportView(inProgressTable);

        javax.swing.GroupLayout inProgressPanelLayout = new javax.swing.GroupLayout(inProgressPanel);
        inProgressPanel.setLayout(inProgressPanelLayout);
        inProgressPanelLayout.setHorizontalGroup(
            inProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inProgressPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );
        inProgressPanelLayout.setVerticalGroup(
            inProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        tabbedMenu.addTab("In Progress", inProgressPanel);

        recentlyResolvedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incident ID", "Report Type", "Report Location", "Responder", "Result", "Other Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(recentlyResolvedTable);

        javax.swing.GroupLayout recentlyResolvedPanelLayout = new javax.swing.GroupLayout(recentlyResolvedPanel);
        recentlyResolvedPanel.setLayout(recentlyResolvedPanelLayout);
        recentlyResolvedPanelLayout.setHorizontalGroup(
            recentlyResolvedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentlyResolvedPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );
        recentlyResolvedPanelLayout.setVerticalGroup(
            recentlyResolvedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        tabbedMenu.addTab("Recently Resolved", recentlyResolvedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = newIncidentTable.getSelectedRow();
        try {
            int id = Integer.parseInt((String) newIncidentTable.getModel().getValueAt(selectedRow, 0));
            try {
                openIncidentResponse(id);
            } catch (IOException ex) {
                Logger.getLogger(SecuritySummaryMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Didn't select incident");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecuritySummaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecuritySummaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecuritySummaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecuritySummaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SecuritySummaryMain().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SecuritySummaryMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    //Opens a new report detail instance for the report with the id 'num'
    public void openReportDetails(int num) throws IOException {
        new ReportDetails(num).setVisible(true);
    }

    public void openIncidentResponse(int num) throws IOException {
        new NewIncidentResponse(num, this).setVisible(true);
    }

    //Adds a listener to the table on tab 3 which listens for a double click and
    //opens a new ReportDetails instance with the id of that report if it hears
    //a double click
    public void initTableListener() {
        recentlyResolvedTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                int id = Integer.parseInt((String) table.getModel().getValueAt(row, 0));
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    try {
                        openReportDetails(id);
                    } catch (IOException ex) {
                        Logger.getLogger(SecuritySummaryMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

        newIncidentTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                int id = Integer.parseInt((String) table.getModel().getValueAt(row, 0));
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    try {
                        openIncidentResponse(id);
                    } catch (IOException ex) {
                        Logger.getLogger(SecuritySummaryMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    public void readNewIncidents() throws FileNotFoundException, IOException {
        URL url = getClass().getResource("NewIncidents.csv");
        try {
            File file = new File(url.getPath());
            String line;
            String[] incident = null;
            DefaultTableModel tableModel = (DefaultTableModel) newIncidentTable.getModel();

            //clear out table of anything that might be in it
            int rowCount = tableModel.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                tableModel.removeRow(0);
            }

            //Add all recentlyResolved reports to the recentlyResolvedTable
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                br.readLine(); //Skip headers
                while ((line = br.readLine()) != null) {

                    //The following regex splits a csv file by commas, but not if they are in quotes
                    incident = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);
                    String[] t = new String[]{incident[0], incident[2], incident[3], incident[1], incident[4]};
                    tableModel.addRow(t);
                }
            }

            //Just here in case we want it later
            rowCount = tableModel.getRowCount();

        } catch (NullPointerException e) {
            //Create a popup saying, we can't find the file
            //Not implemented yet
        }
    }

    public void readReports() throws FileNotFoundException, IOException {
        URL url = getClass().getResource("Reports.csv");
        try {
            File file = new File(url.getPath());
            String line;
            String[] incident = null;
            DefaultTableModel tableModel = (DefaultTableModel) recentlyResolvedTable.getModel();

            //clear out table of anything that might be in it
            int rowCount = tableModel.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                tableModel.removeRow(0);
            }

            //Add all recentlyResolved reports to the recentlyResolvedTable
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                br.readLine(); //Skip headers
                while ((line = br.readLine()) != null) {

                    //The following regex splits a csv file by commas, but not if they are in quotes
                    incident = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);
                    String[] t = new String[]{incident[0], incident[9], incident[6], incident[7], incident[10], incident[3]};
                    tableModel.addRow(t);
                }
            }

            //Just here in case we want it later
            rowCount = tableModel.getRowCount();

        } catch (NullPointerException e) {
            //Create a popup saying, we can't find the file
            //Not implemented yet
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewIncidentsPanel;
    private javax.swing.JPanel inProgressPanel;
    private javax.swing.JTable inProgressTable;
    private javax.swing.JTable incidentQueueTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable newIncidentTable;
    private javax.swing.JPanel recentlyResolvedPanel;
    private javax.swing.JTable recentlyResolvedTable;
    private javax.swing.JPanel tab1Queue;
    private javax.swing.JTabbedPane tabbedMenu;
    // End of variables declaration//GEN-END:variables
}
